const data = [
  {
    uniqueID: 50,
    name: 'Apple - iPhone SE (2nd generation) 64GB - Black (Verizon)',
    description: 'iPhone SE is the powerful 4.7-inch iPhone.¹ Features A13 Bionic, one of the fastest chips in a smartphone, for incredible performance in apps, games, and photography. Portrait mode for studio-quality portraits and six lighting effects. Next-generation Smart HDR for incredible detail across highlights and shadows. Cinematic-quality 4K video. And all the advanced features of iOS. With long battery life² and water resistance³, it\'s so much of the iPhone you love, in a not so big size.',
    brand: 'Apple',
    department: 'Cell Phones',
    color: 'black',
    subDept: 'iPhone',
    sku: 6341338,
    price: 399.99,
    avgRating: 4.7,
    colors: ['Black', 'Red', 'White'],
    reviews: [1,2,3],
    questions: {},
    images: ['https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6341/6341338_sd.jpg;maxHeight=640;maxWidth=550', 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6341/6341338cv11d.jpg;maxHeight=640;maxWidth=550', 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6341/6341338cv12d.jpg;maxHeight=640;maxWidth=550'],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 51,
    name: 'Apple - iPhone 11 Pro Max 64GB - Space Gray (AT&T)',
    description: 'Shoot amazing videos and photos with the Ultra Wide, Wide, and Telephoto cameras. Capture your best low-light photos with Night mode. Watch HDR movies and shows on the 6.5-inch Super Retina XDR display – the brightest iPhone display yet.¹ Experience unprecedented performance with A13 Bionic for gaming, augmented reality (AR), and photography. And get all-day battery life² and a new level of water resistance.³ All in the first iPhone powerful enough to be called Pro.',
    brand: 'Apple',
    department: 'Cell Phones',
    color: 'Space Gray',
    subDept: 'iPhone',
    sku: 6341313,
    price: 1099.99,
    avgRating: 4.9,
    colors: ['Gold', 'Space Gray', 'Midnight Green', 'Silver'],
    reviews: [4],
    questions: {},
    images: ['https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6341/6341313_sd.jpg;maxHeight=640;maxWidth=550', 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6341/6341313cv11d.jpg;maxHeight=640;maxWidth=550', 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6341/6341313cv13d.jpg;maxHeight=640;maxWidth=550'],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 52,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 53,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 54,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 55,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 56,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 57,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 58,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 59,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 60,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 61,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    reviews: [],
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 62,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 63,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 64,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 65,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 66,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 67,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 68,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 69,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 70,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 71,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 72,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 73,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 74,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 75,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 76,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 77,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 78,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 79,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  },
  {
    uniqueID: 80,
    name: ,
    description: ,
    brand: ,
    department: ,
    color: ,
    subDept: ,
    sku: ,
    price: ,
    avgRating: ,
    colors: ,
    reviews: ,
    questions: {},
    images: [],
    peopleAlsoBought: [],
    peopleAlsoViewed: [],
    recentlyViewed: false
  }
]